### ISSUE TITLE
似乎無法使用 DOI 碼？

### ISSUE THREAD

**Issue by Sunethan** [tzhuan/ntu-thesis#19]
我在台大這篇「[二、加入 DOI 碼](http://www.lib.ntu.edu.tw/doc/cl/etdsguide.pdf)」看到，在封面右下角需要有 doi 碼，但是即便我按照最初的設定，在 ntuvars.tex 中放入底下程式碼，也還是沒有在封面看到 doi 碼。

`\doi{doi:10.6342/NTU2017XXXXX}`

![螢幕快照 2019-08-02 下午9 54 20](https://user-images.githubusercontent.com/32844256/62375188-4c257a80-b570-11e9-8698-682c5dd916e7.png)

![螢幕快照 2019-08-02 下午9 56 03](https://user-images.githubusercontent.com/32844256/62375202-56e00f80-b570-11e9-880d-4467709bf871.png)

還請大大幫忙一下...真的很感謝您。LaTeX 真的省了我很多很多的排版功夫！

**Comment by tzhuan** [comment]
如果您使用 `make` 的話，用 `make DOI=1` 應該能產生帶有 doi 的 pdf 文件。

而如果您不是使用 `make` 的話，請在 `thesis.tex` 的設定字型之後加上一些設定：
```latex
\setCJKmainfont{標楷體} % 設定中文字型

\def\withdoi{1}  % DOI 支援請加上這行
\def\firstpage{1} % 如果首頁要有浮水印和 DOI 請加上這行
\def\excludefirstpage{1} % 如果首頁不要有浮水印和 DOI 則加上這行
```

**Comment by Sunethan** [comment]
太好了！終於出現 DOI 囉，感謝您 :) 不好意思這麼晚才回覆，真的非常謝謝您！
