### ISSUE TITLE
Weird Error

### ISSUE THREAD

**Issue by huw12313212** [tzhuan/ntu-thesis#3]
不好意思，我按照了下面這個教學來Build Latex。
http://www.teeboneding.com/blog/2013/06/01/write-ntu-master-thesis-with-xelatex-template-on-mac/
但是做到最後在Build的時候會跑出下面這個錯誤：
https://dl.dropboxusercontent.com/u/6400586/Error.png
不知道是不是哪邊我沒注意到ＱＱ？

**Comment by tzhuan** [comment]
看起來你不是用 XeLaTeX 來建立？

**Comment by huw12313212** [comment]
我發現問題了ＱＱ

因為我之前用Sublime的外掛，直接按comman + B就會build出latex....

後來才發現要用terminal按make....

Sorry我耍笨惹ＱＱ

**Comment by tzhuan** [comment]
那個連結有教學如何修改 sublime 改用 xelatex，試試看吧~
