### ISSUE TITLE
使用 \makespine 會出現編譯錯誤

### ISSUE THREAD

**Issue by moneycat** [tzhuan/ntu-thesis#8]
```
...

\setCJKmainfont{AR PL UMing TW}
\setCJKfamilyfont{sidepagefont}[Vertical=RotatedGlyphs]{AR PL UMing TW} %額外定義 makespine 需要 的 sidepagefont 資訊

...

\makecover
\makespine

...
```

編譯時會出現以下錯誤

> ! LaTeX Error: There's no line here to end.
> 
> See the LaTeX manual or LaTeX Companion for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                   
> l.71 \makespine
>                
> ? 
>

**Comment by tzhuan** [comment]
當初設計時因中文直排有諸多問題無法克服，且書背僅供印刷用，並非論文的一部份，所以這個功能並沒有完成。若您有任何建議或修正，歡迎 pull request！:)

**Comment by moneycat** [comment]
謝謝您，的確很難處理。先 close issue，如果有機會找到解答再說。
